name: RedirectToChild
version: 1.0.0
description: Automatically redirects to the first child
url: https://github.com/lesaff/statamic-redirecttochild
developer: Rudy Affandi
developer_url: https://github.com/lesaff
