name: Redirect To Child
version: 1.0.1
description: Automatically redirects to the first child
url: https://github.com/lesaff/statamic2-redirecttochild
developer: Rudy Affandi
developer_url: https://github.com/lesaff
